2023/11/19 03:34:41 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.4:9000", host: "localhost"
2023/11/19 09:48:54 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "localhost", referrer: "http://localhost/"
2023/11/19 09:49:07 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "localhost", referrer: "http://localhost/"
2023/11/19 16:04:14 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "localhost", referrer: "http://localhost/"
2023/11/19 16:04:17 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "localhost", referrer: "http://localhost/"
2023/11/19 16:04:22 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "localhost", referrer: "http://localhost/"
2023/11/21 13:01:34 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "localhost"
